
services:
  redis:
    image: redis
    container_name: dev-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - resell_net

  python:
    build: ./backend/python_server
    container_name: dev-python
    volumes:
      - ./backend/python_server:/app
    ports:
      - "5000"
    networks:
      - resell_net

networks:
  resell_net:

volumes:
  redis_data: